### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by yatga** [Reepeecheep/NumberGuesser#12]
In logcat I see this error:

~~~
FATAL EXCEPTION: main
Process: com.numguesser.tonio_rpchp.numberguesser, PID: 2221
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.numguesser.tonio_rpchp.numberguesser/com.numguesser.tonio_rpchp.numberguesser.Guesser}: android.content.res.Resources$NotFoundException: Drawable com.numguesser.tonio_rpchp.numberguesser:dimen/compat_button_inset_vertical_material with resource ID #0x7f060056
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.numguesser.tonio_rpchp.numberguesser:dimen/compat_button_inset_vertical_material with resource ID #0x7f060056
Caused by: android.content.res.Resources$NotFoundException: Resource "com.numguesser.tonio_rpchp.numberguesser:dimen/compat_button_inset_vertical_material" (7f060056) is not a Drawable (color or path): TypedValue{t=0x5/d=0x601 a=4 r=0x7f060056}
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:897)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:769)
	at android.content.res.Resources.getDrawable(Resources.java:834)
	at android.content.res.XResources.getDrawable(XResources.java:790)
	at android.content.Context.getDrawable(Context.java:529)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
	at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:86)
	at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
	at com.numguesser.tonio_rpchp.numberguesser.Guesser.switch_image(Guesser.java:306)
	at com.numguesser.tonio_rpchp.numberguesser.Guesser.onCreate(Guesser.java:128)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2749)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
~~~

It seems like some resource is missing? I'm using the latest f-droid version, 5.0, on Android 7.0. The previous release didn't have this issue.

Is there anything else I could provide?

**Comment by Reepeecheep** [comment]
Hi, thanks for you report, Can you compile the new version in your device and verify please?

**Comment by yatga** [comment]
Thanks Reepeecheep! However I don't have a development environment to compile this, could you share your built apk (on something like https://dro.pm) for testing?
